### ISSUE TITLE
【留言】🥳非常荣幸地发现了您的GitHub主页

### ISSUE THREAD

**Issue by iTomstudio** [wanggangwei82/wanggangwei82.github.io#8]
作为曾经HUEB数统学院学生，非常荣幸地发现了您的GitHub主页🎉
衷心祝愿您在自己所热爱的的发展中取得更加优异的成果！🥇
祝好😀

**Comment by wanggangwei66** [comment]
谢谢。欢迎回母校看看。

**Comment by wanggangwei66** [comment]
您好， 您给我的邮件已收到， 我会尽快处理。谢谢。Best RegardsGangwei Wang  (H-index =22)School of Mathematics and Statistics, 
Hebei University of Economics and Business
